### ISSUE TITLE
Could not process your request - after Pressing Know Your HAIgenie Score

### ISSUE THREAD

**Issue by datakalp** [datakalp/Vajra-Hands-App#13] opened 2023-04-13 03:07 UTC
OnePlus Nord 2
![WhatsApp Image 2023-04-13 at 08 35 10](https://user-images.githubusercontent.com/50823421/231637938-07069589-f22b-4cd2-b56e-dbb5a776c957.jpg)

**Comment by datakalp** [comment] 2023-04-13 03:21
Happened multiple times today morning.  Not sure if the recordings also went through.

**Comment by anubhutiGupta** [comment] 2023-04-13 03:44
This error is related to the metadata not being able to save in our Local MySQL DB in the VM (randomly after a while); The recordings were successfully uploaded.

**Comment by aniketpingley** [comment] 2023-04-17 04:22
Not producible anymore.

**Comment by datakalp** [comment] 2023-04-18 04:41
This was observed yesterday again by two people. So reopening it.

**Comment by anubhutiGupta** [comment] 2023-04-18 05:53
Steps that might reproduce the error :-
1. Successfully login ; perform handwash ; go to compliance screen successfully and view feedback
2. From the compliance screen ; click on the **red re-record button** to re-record ; which takes back to record screen
3. Perform handwash ; then click on **Know your HAIgenie Score** button

PS repeating steps 2 and 3 up to three-four times, might reproduce the error

**Comment by anubhutiGupta** [comment] 2023-04-24 10:58
This issue hasn't been reported from quite a while, we can close this after trying to reproduce this following the above steps; for a day or two.

**Comment by anubhutiGupta** [comment] 2023-04-26 08:14
This issue hasn't been re-reported so we can close this, since it's not reproducible any more

**Closed** 2023-04-26 13:20 UTC
Labels: bug, P0
